/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class AddjPanel extends javax.swing.JPanel {

    
    /**
     * Creates new form AddjPanel
     */
    public AddjPanel() {
        initComponents();
        this.prom = new ArrayList <String>();
        this.nombre =" ";
        this.cedula =" ";
        this.ciudad =" ";
        this.partido =" ";
        this.inclinacion =" ";
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextfNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFcedula = new javax.swing.JTextField();
        jComboBoxCity = new JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jCheckBoxDerecha = new javax.swing.JCheckBox();
        jCheckBoxIzquierda = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxPartido = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFpromesas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();

        setBackground(new java.awt.Color(187, 187, 187));
        setMaximumSize(new java.awt.Dimension(643, 377));
        setMinimumSize(new java.awt.Dimension(643, 377));
        setPreferredSize(new java.awt.Dimension(643, 377));

        jPanel1.setBackground(new java.awt.Color(187, 187, 187));
        jPanel1.setMaximumSize(new java.awt.Dimension(643, 337));
        jPanel1.setMinimumSize(new java.awt.Dimension(643, 337));
        jPanel1.setPreferredSize(new java.awt.Dimension(643, 337));

        jLabel1.setText("Nombre:");

        jLabel2.setText("Cedula:");


        ArrayList<String> listaCiudades = new ArrayList<String>();
        for (C_origen ciudades : C_origen.values() ) {
            listaCiudades.add(ciudades.displayNameEnum());
            
        }
        jComboBoxCity.setModel(new javax.swing.DefaultComboBoxModel<>(listaCiudades.toArray(new String[0])));

        jLabel3.setText("Ciudad de origen:");

        jCheckBoxDerecha.setText("Derecha");
        jCheckBoxDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDerechaActionPerformed(evt);
            }
        });

        jCheckBoxIzquierda.setText("Izquierda");
        jCheckBoxIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxIzquierdaActionPerformed(evt);
            }
        });

        jLabel4.setText("Ideologia:");

        ArrayList<String> listaPartidos = new ArrayList<String>();
        for (Partido_p partido : Partido_p.values() ) {
            listaPartidos.add(partido.displayNameEnum());
            
        }

        jComboBoxPartido.setModel(new javax.swing.DefaultComboBoxModel<>(listaPartidos.toArray(new String[0])));

        jLabel5.setText("Partido Politico:");



        jLabel6.setText("Promesas:");

        jButtonAdd.setBackground(new java.awt.Color(187, 187, 187));
        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("agregar-archivo.png"))); // NOI18N
        jButtonAdd.setText("Agregar");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jCheckBoxIzquierda)
                                .addComponent(jButtonAdd)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(129, 129, 129))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFpromesas, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBoxDerecha)
                                .addGap(209, 209, 209)
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxDerecha)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFpromesas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBoxIzquierda)
                        .addGap(42, 42, 42)
                        .addComponent(jButtonAdd)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents



    private void jCheckBoxDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDerechaActionPerformed
        if(jCheckBoxDerecha.isSelected() && jCheckBoxIzquierda.isSelected()){
            jCheckBoxIzquierda.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBoxDerechaActionPerformed

    private void jCheckBoxIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxIzquierdaActionPerformed
        if(jCheckBoxDerecha.isSelected() && jCheckBoxIzquierda.isSelected()){
            jCheckBoxDerecha.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBoxIzquierdaActionPerformed

    private void reiniciarVariables(){
        jTextfNombre.setText(null);
        jTextFcedula.setText(null);
        jTextFpromesas.setText(null);
        this.prom = new ArrayList <String>();
        this.nombre =" ";
        this.cedula =" ";
        this.ciudad =" ";
        this.partido =" ";
        this.inclinacion =" ";
        jCheckBoxDerecha.setSelected(false);
        jCheckBoxIzquierda.setSelected(false);
        

    }

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {
        // codeOf: Agregar Candidato y excepcion si no llena todos los campos
        try{
            for(int i = 0; i < AddjPanel.candidatos.size(); i++){
                if(AddjPanel.candidatos.get(i).getCedula().equals(jTextFcedula.getText())){
                throw new FormularioException("La cedula que digitaste ya se ha ingresasdo");
                
                }
                
            }

        if(jTextfNombre.getText().equals("") == false && jTextFcedula.getText().equals("") == false && (jCheckBoxIzquierda.isSelected()|| jCheckBoxDerecha.isSelected()) && jTextFpromesas.getText().equals("") == false){
        this.nombre = jTextfNombre.getText();
        this.cedula = jTextFcedula.getText();
        this.ciudad = ((String) jComboBoxCity.getSelectedItem()).replace(" ", "_");
        this.ciudad.replace(" ", "_");
        this.partido = ((String) jComboBoxPartido.getSelectedItem()).replace(" ", "_");
        this.ciudad.replace(" ", "_");
        this.partido.replace(" ", "_");
        this.prom.add(jTextFpromesas.getText());
        if(jCheckBoxDerecha.isSelected()){
            this.inclinacion = "DERECHA";
        }
        else if(jCheckBoxIzquierda.isSelected()){
            this.inclinacion = "IZQUIERDA";
        }
        candidatos.add(new Candidato(this.nombre,this.cedula,C_origen.valueOf(this.ciudad.toUpperCase()),Partido_p.valueOf(this.partido.toUpperCase()),this.prom,Inclinacion.valueOf(this.inclinacion),0));
        reiniciarVariables();
        }
        else{
            throw new FormularioException("¡Debes llenar todos los campos del candidato!");
        }  }
        catch(FormularioException ex){
            JOptionPane.showMessageDialog(jPanel1,ex.getMessage()); 
        }
        
        
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JCheckBox jCheckBoxDerecha;
    private javax.swing.JCheckBox jCheckBoxIzquierda;
    private javax.swing.JComboBox<String> jComboBoxCity;
    private javax.swing.JComboBox<String> jComboBoxPartido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFcedula;
    private javax.swing.JTextField jTextFpromesas;
    private javax.swing.JTextField jTextfNombre;
    public ArrayList <String> prom;
    public String nombre,cedula,partido,ciudad,inclinacion;
    static ArrayList<Candidato> candidatos = new ArrayList<>();
    // End of variables declaration//GEN-END:variables
}
