/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.miniproyecto2;

/**
 *
 * @author usuario
 */
public class GraficaUser extends javax.swing.JFrame {

    /**
     * Creates new form GraficaUser
     */
    public GraficaUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGUI = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuAdd = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuDelete = new javax.swing.JMenu();
        jMenuShow = new javax.swing.JMenu();
        jMenuUpdate = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(115, 125, 188));
        setMaximumSize(new java.awt.Dimension(635, 400));
        setMinimumSize(new java.awt.Dimension(635, 400));
        setResizable(false);

        jPanelGUI.setBackground(new java.awt.Color(255, 255, 255));
        jPanelGUI.setMaximumSize(new java.awt.Dimension(643, 377));
        jPanelGUI.setMinimumSize(new java.awt.Dimension(643, 377));
        jPanelGUI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanelGUI, java.awt.BorderLayout.CENTER);

        jMenuAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/miniproyecto2/imageSources/agregar.png"))); // NOI18N
        jMenuAdd.setText("Agregar");
        jMenuBar2.add(jMenuAdd);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/miniproyecto2/imageSources/buscar.png"))); // NOI18N
        jMenu2.setText("Buscar");
        jMenuBar2.add(jMenu2);

        jMenuDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/miniproyecto2/imageSources/borrar.png"))); // NOI18N
        jMenuDelete.setText("Eliminar");
        jMenuBar2.add(jMenuDelete);

        jMenuShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/miniproyecto2/imageSources/ver.png"))); // NOI18N
        jMenuShow.setText("Ver");
        jMenuBar2.add(jMenuShow);

        jMenuUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/miniproyecto2/imageSources/actualizado.png"))); // NOI18N
        jMenuUpdate.setText("Actualizar");
        jMenuBar2.add(jMenuUpdate);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/miniproyecto2/imageSources/garrapata.png"))); // NOI18N
        jMenu4.setText("Continuar");
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraficaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraficaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraficaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraficaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraficaUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenuAdd;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuDelete;
    private javax.swing.JMenu jMenuShow;
    private javax.swing.JMenu jMenuUpdate;
    private javax.swing.JPanel jPanelGUI;
    // End of variables declaration//GEN-END:variables
}
